"""schema change

Revision ID: 3034bffa0236
Revises: 094e5a0d70e3
Create Date: 2024-02-08 23:48:26.100141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3034bffa0236'
down_revision = '094e5a0d70e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(precision=range(0, 30)), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('home_pages')
    op.drop_table('search_icons')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_icons',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('url', sa.VARCHAR(length=256), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('home_page_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['home_page_id'], ['home_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('home_pages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=256), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('foods')
    # ### end Alembic commands ###
