"""schema change1

Revision ID: 75d9301fe0f8
Revises: 3a50a1d44c73
Create Date: 2024-02-09 00:51:43.142419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d9301fe0f8'
down_revision = '3a50a1d44c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('adress', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_column('adress')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
